apiVersion: v1
kind: Deployment
metadata:
  name: session-simulator
  namespace: session-simulator
  labels:
    app: session-simulator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: session-simulator
  template:
    metadata:
      labels:
        app: session-simulator
    spec:
      containers:
        - name: session-simulator
          image: saltandpurple/session-simulator:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: session-simulator
  namespace: session-simulator
spec:
  selector:
    app: session-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: session-simulator
  namespace: session-simulator
  annotations:
    haproxy-ingress.github.io/affinity: cookie
    haproxy-ingress.github.io/controller: haproxy
    haproxy-ingress.github.io/rewrite-target: /
spec:
  ingressClassName: haproxy
  rules:
    - http:
        paths:
          - path: /session-simulator
            pathType: Prefix
            backend:
              service:
                name: session-simulator
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: session-simulator
  namespace: session-simulator
data:
  preStop.sh: |
    #!/bin/bash
    echo "this will be the prestop hook script"